vpn_network_cidr: "10.0.0.0/24"
vpn_listen_port: 51820
ssh_port: 2222

vpn_peers:
  - name: vpn
    index: 0
  - name: db
    index: 1
  - name: mon
    index: 2

host_index: >
  {% if inventory_hostname == 'vpn' %}0
  {% elif inventory_hostname == 'db' %}1
  {% elif inventory_hostname == 'mon' %}2
  {% else %}10{% endif %}
