version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    network_mode: host

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@127.0.0.1:5432/mydb?sslmode=disable"
      WEB_LISTEN_ADDRESS: "10.0.0.11:9187"
    network_mode: host

  redis:
    image: redis:7
    network_mode: host

  redis_exporter:
    image: oliver006/redis_exporter
    environment:
      REDIS_ADDR: redis://127.0.0.1:6379
      WEB_LISTEN_ADDRESS: "10.0.0.11:9121"
    network_mode: host
