global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['10.0.0.11:9187']
  - job_name: 'redis'
    static_configs:
      - targets: ['10.0.0.11:9121']
