- name: Install iptables
  ansible.builtin.package:
    name: 
      - iptables
      - iptables-persistent
    state: present

- name: Deploy iptables rules
  ansible.builtin.template:
    src: iptables.rules.j2
    dest: /etc/iptables/rules.v4
  become: true

- name: Restore iptables rules
  ansible.builtin.shell: iptables-restore < /etc/iptables/rules.v4
  become: true


